import React, { useState } from 'react';
import { Case } from '../types';
import { generateLegalNotice } from '../services/geminiService';
import { Printer, Copy, Globe, FileSignature, Loader2, Check, PenTool, Lock, Crown } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';
import { useSubscription } from '../contexts/SubscriptionContext';

interface Props {
  currentCase: Case;
}

const LetterGenerator: React.FC<Props> = ({ currentCase }) => {
  const { t } = useLanguage();
  const { isPremium, setShowPaywall } = useSubscription();
  const [loading, setLoading] = useState(false);
  const [letter, setLetter] = useState<{ subject: string; englishBody: string; arabicBody: string } | null>(null);
  const [viewLang, setViewLang] = useState<'en' | 'ar'>('en');
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const result = await generateLegalNotice(currentCase);
      setLetter(result);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!letter) return;
    const text = viewLang === 'en' ? letter.englishBody : letter.arabicBody;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    if (!letter) return;
    const printWindow = window.open('', '', 'width=800,height=600');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Formal Notice - ${currentCase.title}</title>
            <style>
              body { font-family: 'Times New Roman', serif; padding: 40px; line-height: 1.6; max-width: 800px; margin: 0 auto; }
              h2 { text-align: center; text-decoration: underline; margin-bottom: 30px; }
              .content { white-space: pre-wrap; font-size: 14px; }
              .footer { margin-top: 50px; font-style: italic; font-size: 12px; color: #666; text-align: center; border-top: 1px solid #ccc; padding-top: 10px;}
            </style>
          </head>
          <body>
            <h2>${letter.subject}</h2>
            <div class="content" dir="${viewLang === 'ar' ? 'rtl' : 'ltr'}">${viewLang === 'en' ? letter.englishBody : letter.arabicBody}</div>
            <div class="footer">Generated by WageGuard - UAE Labour Rights Assistant</div>
            <script>window.print();</script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  // --- PREMIUM GATE ---
  if (!isPremium) {
    return (
      <div className="bg-white rounded-[2rem] border border-slate-100 shadow-xl shadow-slate-200/40 overflow-hidden relative min-h-[450px] flex flex-col items-center justify-center p-8 text-center animate-fade-in-up">
          {/* Blurred Background Hint */}
          <div className="absolute inset-0 bg-white z-0">
              <div className="absolute top-10 left-10 right-10 bottom-10 opacity-30 blur-[2px] select-none pointer-events-none text-left font-serif text-sm leading-loose text-slate-800">
                  <span className="font-bold">Subject: FORMAL NOTICE OF GRIEVANCE</span><br/><br/>
                  To the General Manager,<br/><br/>
                  I am writing to formally request the immediate settlement of my outstanding dues, specifically regarding [Unpaid Salary].<br/>
                  According to <span className="bg-indigo-100">Article 22 of the Federal Decree-Law No. 33</span> of 2021 regarding the Regulation of Labour Relations, the employer is obligated to pay wages on their due dates.<br/>
                  Failure to settle these amounts within 7 days will leave me no choice but to register a formal complaint...
              </div>
              <div className="absolute inset-0 bg-gradient-to-b from-white/70 via-white/95 to-white"></div>
          </div>

          <div className="relative z-10 max-w-md mx-auto">
              <div className="bg-gradient-to-br from-royal-50 to-indigo-50 p-5 rounded-full inline-block mb-6 shadow-sm ring-4 ring-white">
                  <FileSignature className="w-12 h-12 text-royal-600" strokeWidth={1.5} />
              </div>
              
              <h2 className="text-2xl font-extrabold text-slate-900 mb-3 tracking-tight">
                  Formal Legal Notice Generator
              </h2>
              <p className="text-slate-500 text-sm leading-relaxed mb-8 font-medium">
                  Don't know what to write? Instantly draft a professional demand letter citing specific <strong>UAE Labour Law Articles</strong> in both <strong>English & Arabic</strong>. 
              </p>

              <button 
                  onClick={() => setShowPaywall(true)}
                  className="w-full bg-slate-900 text-white font-bold py-4 rounded-2xl shadow-xl shadow-slate-900/20 hover:bg-black transition transform hover:scale-105 active:scale-95 flex items-center justify-center group"
              >
                  <Lock className="w-4 h-4 mr-2 text-amber-400 group-hover:text-amber-300 transition-colors" />
                  Unlock Premium Feature
              </button>
              
              <div className="mt-5 flex items-center justify-center space-x-4 text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                  <span className="flex items-center"><Check className="w-3 h-3 mr-1 text-emerald-500" /> English & Arabic</span>
                  <span className="flex items-center"><Check className="w-3 h-3 mr-1 text-emerald-500" /> Law Citations</span>
              </div>
          </div>
      </div>
    );
  }

  // --- PREMIUM VIEW ---
  return (
    <div className="space-y-6">
      {!letter ? (
        <div className="bg-white rounded-[2rem] border border-slate-100 shadow-xl shadow-slate-200/40 p-8 text-center animate-fade-in-up">
           <div className="bg-slate-50 p-6 rounded-full inline-block mb-6 border border-slate-100">
               <FileSignature className="w-12 h-12 text-slate-400" strokeWidth={1.5} />
           </div>
           <h2 className="text-2xl font-extrabold text-slate-900 mb-2">Formal Grievance Notice</h2>
           <p className="text-slate-500 max-w-sm mx-auto mb-8 leading-relaxed">
               Generate a professional legal demand letter citing specific UAE Labour Law articles. 
               Send this to your employer before filing a MOHRE complaint.
           </p>
           
           <button 
             onClick={handleGenerate}
             disabled={loading}
             className="bg-royal-900 text-white font-bold py-4 px-8 rounded-2xl shadow-xl shadow-royal-900/20 hover:bg-royal-800 transition transform hover:scale-105 active:scale-95 disabled:opacity-70 disabled:scale-100 flex items-center mx-auto"
           >
             {loading ? <Loader2 className="animate-spin mr-2" /> : <PenTool className="w-5 h-5 mr-2" />}
             {loading ? "Drafting with AI..." : "Generate Official Letter"}
           </button>
        </div>
      ) : (
        <div className="animate-in fade-in slide-in-from-bottom-8 duration-500">
            {/* Toolbar */}
            <div className="flex justify-between items-center mb-4 bg-slate-100 p-2 rounded-xl">
                 <div className="flex space-x-1">
                     <button 
                       onClick={() => setViewLang('en')}
                       className={`px-4 py-2 rounded-lg text-xs font-bold transition ${viewLang === 'en' ? 'bg-white shadow-sm text-royal-900' : 'text-slate-500 hover:text-slate-700'}`}
                     >
                         English
                     </button>
                     <button 
                       onClick={() => setViewLang('ar')}
                       className={`px-4 py-2 rounded-lg text-xs font-bold transition ${viewLang === 'ar' ? 'bg-white shadow-sm text-royal-900' : 'text-slate-500 hover:text-slate-700'}`}
                     >
                         العربية
                     </button>
                 </div>
                 <div className="flex space-x-2">
                     <button onClick={handleCopy} className="p-2 text-slate-500 hover:bg-white hover:text-royal-700 rounded-lg transition" title="Copy Text">
                         {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                     </button>
                     <button onClick={handlePrint} className="p-2 text-slate-500 hover:bg-white hover:text-royal-700 rounded-lg transition" title="Print PDF">
                         <Printer className="w-4 h-4" />
                     </button>
                 </div>
            </div>

            {/* Paper View */}
            <div className="bg-white p-8 md:p-12 rounded-xl shadow-sm border border-slate-200 min-h-[500px] relative">
                {/* Paper Texture Effect */}
                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cream-paper.png')] opacity-30 pointer-events-none"></div>
                
                <div className={`relative z-10 ${viewLang === 'ar' ? 'text-right' : 'text-left'}`} dir={viewLang === 'ar' ? 'rtl' : 'ltr'}>
                    <h3 className="text-xl font-bold text-slate-900 mb-8 uppercase text-center underline decoration-slate-300 underline-offset-4">
                        {letter.subject}
                    </h3>
                    
                    <div className="whitespace-pre-wrap text-slate-800 font-serif leading-loose text-sm md:text-base">
                        {viewLang === 'en' ? letter.englishBody : letter.arabicBody}
                    </div>

                    <div className="mt-12 pt-8 border-t border-slate-100 flex justify-between items-end text-xs text-slate-400 font-mono">
                         <span>Generated via WageGuard</span>
                         <span>{new Date().toLocaleDateString()}</span>
                    </div>
                </div>
            </div>

            <button 
                onClick={() => setLetter(null)}
                className="w-full mt-6 py-4 text-slate-500 font-bold text-sm hover:text-slate-700 transition"
            >
                Start Over
            </button>
        </div>
      )}
    </div>
  );
};

export default LetterGenerator;